version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build-and-push:
    resource_class: small
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: kkristian/orb-test
      - docker/push:
          digest-path: /tmp/digest.txt
          image: kkristian/orb-test
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
      - run:
          command: |
            echo "$PRACTICE_VARIABLE"
workflows:
  commit:
    jobs:
      - build-and-push
