version: 2.1
orbs:
  docker: circleci/docker@2.2.0

# Jobs
jobs:
  build-and-push:
    resource_class: medium
    executor: docker/docker
    steps:
      - setup_remote_docker
      - save_cache:
          paths:
            - /root/.docker
          key: docker-layers-{{ checksum "Dockerfile" }}
      - checkout
      - docker/check
      - docker/build:
          image: kkristian/orb-test
      - restore_cache:
          key: docker-layers-{{ checksum "Dockerfile" }}
      - docker/push:
          digest-path: /tmp/digest.txt
          image: kkristian/orb-test
      - save_cache:
          key: docker-layers-{{ checksum "Dockerfile" }}
          paths:
            - /root/.docker
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
      - run:
          command: |
            echo "$PRACTICE_VARIABLE"

# Workflows
workflows:
  commit:
    jobs:
      - build-and-push
